### ISSUE TITLE
Add a century key to the DateTime.change method

### ISSUE THREAD

**Issue by alexmorten** [alexmorten/rails#6]
We are working with centuries a LOT, so having the option to call `DateTime.new(2012, 8, 29, 22, 35, 0).change(century: 18, year: 2013) => DateTime.new(1713, 8, 29, 22, 35, 0)` Would be a huge timesaver. 

One way to do this would be to extend the `DateTime` class and simply call the old change method with updated parameters.
For example, given the parameters `century: 23` and `year: 1846` we want to call the old change method with `year: 2346`, so something along the lines of `(23-1)*100 + 1846 % 100`

Don't forget to add a  getter method for century, since this implementation would just be a shallow extension of the `year` attribute

**Comment by mercutiodesign** [comment]
Do you want the year 1801 to be in the 18th century or the 19th?

**Comment by alexmorten** [comment]
good call I always mess this up
